// Generates the C++ lookup table used by src/emoji.cpp.
// Usage: node tools/generateEmojiShortcodes.js path/to/gemoji/db/emoji.json
const fs = require("fs");
const path = require("path");

if (process.argv.length !== 3) {
    throw new Error("Expected the path to github/gemoji db/emoji.json");
}

const records = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
const aliases = new Map();
for (const record of records) {
    if (!record.emoji) continue;
    for (const alias of record.aliases || []) aliases.set(alias, record.emoji);
}

const cppString = value => Array.from(Buffer.from(value, "utf8"))
    .map(byte => `\\x${byte.toString(16).padStart(2, "0").toUpperCase()}`)
    .join("");
const cppAlias = value => value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const rows = [...aliases.entries()]
    // Match C strcmp ordering used by the generated table's binary search.
    .sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)
    .map(([alias, emoji]) => `    { "${cppAlias(alias)}", "${cppString(emoji)}" },`)
    .join("\n");

const output = `// Generated by tools/generateEmojiShortcodes.js; do not edit by hand.
// Data source: https://github.com/github/gemoji (MIT License).
#pragma once

#include <cstddef>

struct EmojiShortcodeEntry
{
    const char* alias;
    const char* emoji;
};

static const EmojiShortcodeEntry EMOJI_SHORTCODES[] = {
${rows}
};

static const std::size_t EMOJI_SHORTCODE_COUNT =
    sizeof(EMOJI_SHORTCODES) / sizeof(EMOJI_SHORTCODES[0]);
`;

const outputPath = path.join(__dirname, "..", "src", "emojiShortcodes.generated.h");
fs.writeFileSync(outputPath, output);
console.log(`Generated ${aliases.size} aliases in ${outputPath}`);
